stages:
  load_data:
    cmd: python src/load_data.py --config=config/params.yml
    deps:
    - src/get_data.py
    - src/load_data.py
    - given_data/winequality.csv
    outs:
    - data/raw/winequality.csv