data_source:
  s3_source: given_data/winequality.csv

raw_data:
  raw_data_path: data/raw/winequality.csv

split_data:
  test_data_path: data/processed/test_winequality.csv
  train_data_path: data/processed/train_winequality.csv
  split_data_path: 
  split_ratio: 0.2
  random_state: 123

train_evaluate:
  model_store_dir: saved_models
  target_col: TARGET 
  # alpha: 0.75
  # l1_ratio: 0.5
  # alpha: 0.9
  # l1_ratio: 0.5
  alpha: 0.9
  l1_ratio: 0.8

reports:
  params_json: reports/params.json
  scores_json: reports/scores.json


